apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: microbot-ingress
 annotations:
   cert-manager.io/cluster-issuer: lets-encrypt
spec:
 tls:
 - hosts:
   - test1.jnguiot.fr
   secretName: collectives-ingress-tls
 rules:
 - host: test1.jnguiot.fr
   http:
     paths:
     - backend:
         service:
           name: collectives
           port:
             number: 5000
       path: /
       pathType: Prefix
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: lets-encrypt
spec:
 acme:
   email: microk8s@yopmail.com
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: lets-encrypt-private-key
   # Add a single challenge solver, HTTP01 using nginx
   solvers:
   - http01:
       ingress:
         class: public
---
apiVersion: v1
kind: Service
metadata:
  name: collectives
  labels:
    app: collectives
spec:
  ports:
    - port: 5000
  selector:
    app: collectives
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collectives
  labels:
    app: collectives
spec:
  selector:
    matchLabels:
      app: collectives
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: collectives
        tier: frontend
    spec:
      containers:
      - image: cafannecy/collectives:vx3
        name: collectives
        env:
        ports:
        - containerPort: 5000
          name: collectives
        volumeMounts:
        - name: collectives-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: collectives-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-volume
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/app/static/uploads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi